### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by jeffallen**
Have a look, see what you think.

A working version is on (with lang selection in URL): https://jeffallen.github.io/COVID_19_CH/?lang=fr

You can also see it by setting your browser language priority to French, and then navigating to: https://jeffallen.github.io/COVID_19_CH

If you like this technique, then I will proceed with the rest of the work, to French, English and Italian. (You'll have to find your own Romansch speaker.)

### CODE REVIEW

**Comment by rsalzer** [comment]
Thank you Jeff.
It seems to work well for hard-coded Strings in the HTML. For the dynamic code it works if I put the load()-function at the end. For the diagrams it does not seem to work.
Maybe there we would have to use a translation-function directly.

**Comment by jeffallen** [comment]
Yes, the diagrams will need additional calls to "".toLocaleString()", which I will take care of. So I will go forward with the rest of the job, and you'll see it as a few more commits on this PR.

**Comment by jeffallen** [comment]
The HTML is fully translated now, at least the stuff you can see on the screen. There are still some tooltips not translated, I need to work on the DOM walker for that.

Content created by script.js is next.

**Comment by rsalzer** [comment]
Tooltips etc. is all in script.js

**Comment by jeffallen** [comment]
OK, this is ready to merge, if you'd like. I will come back with a second PR with EN and IT in it.

**Pull request merged**
