### PR TITLE
Added missing slashes

### PR DESCRIPTION
**Pull request by FlashJunior**

### CODE REVIEW

**Comment by rsalzer** [comment]
thank you ... but as i am still further developing the script, a minified version does not make any sense (also, the code is still short...)

**Comment by FlashJunior** [comment]
on mobile, every **kb** counts ;-)
image

For automatic "minifying" you can work with tools like [Codekit](https://codekitapp.com/), grunt, gulp..

**Comment by rsalzer** [comment]
true ... how do you minimize the script? If i could automate that, I would certainly do it. Otherwise, I am just changing the script still too often.

**Comment by FlashJunior** [comment]
For automatic "minifying" you can work with tools like [Codekit](https://codekitapp.com/), grunt, gulp..

**Pull request closed without merging**
